language: go

go:
    - 1.4

before_install:
    - go get github.com/smartystreets/goconvey
    - go get golang.org/x/net/websocket
    - go get github.com/gorilla/sessions
    - go get github.com/mattn/go-sqlite3
    - go get github.com/satori/go.uuid
    - go get github.com/BurntSushi/toml

install:
    - go get -d -v ./...
